# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "parse"
  parse:
    # The type of runner that the job will run on
    container: openmodelica/openmodelica:v1.16.2-minimal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create the script
        run: echo 'b:=loadFile("Physiolibrary/package.mo");getErrorString();exit(if b then 0 else 1)' > parse.mos

      - name: Parse the library
        run: omc parse.mos
